import { Settings, Operation } from './cam-gcode';

export const defaultSettings: Settings = {
    comAccumulatedJobTime: 0,
    comInterfaces: [],
    comPorts: [],
    comServerConnect: false,
    comServerIP: 'localhost:8000',
    comServerVersion: 'not connected',
    connectBaud: '115200',
    connectIP: '',
    connectPort: '',
    connectVia: '',
    dpiBitmap: 300,
    forcePxPerInch: false,
    gcodeCheckSizePower: 0,
    gcodeConcurrency: 2,
    gcodeCurvePrecision: 0.1,
    gcodeEnd: 'M5; Switch tool off\nEnd',
    gcodeGenerator: 'default',
    gcodeHoming: '',
    gcodeLaserIntensity: 'S',
    gcodeLaserIntensitySeparateLine: false,
    gcodeSMaxValue: 1,
    gcodeSMinValue: 0,
    gcodeStart: 'G21; Set units to mm\nG90; Absolute positioning',
    gcodeToolOff: '',
    gcodeToolOn: '',
    gcodeToolTestDuration: 0,
    gcodeToolTestPower: 0,
    jogFeedXY: 1800,
    jogFeedZ: 300,
    jogStepsize: 1,
    machineAEnabled: false,
    machineBeamDiameter: 0.2,
    machineBlowerEnabled: false,
    machineBlowerGcodeOff: '',
    machineBlowerGcodeOn: '',
    machineBottomLeftX: 0,
    machineBottomLeftY: 0,
    machineFeedRange: {
        A: {min: 1, max: 50000},
        S: {min: 0, max: 30000},
        XY: {min: 1, max: 50000},
        Z: {min: 1, max: 50000},
    },
    machineHeight: 200,
    machineWidth: 300,
    machineXYProbeOffset: 0,
    machineZEnabled: false,
    machineZMatThickness: 0,
    machineZProbeOffset: 0,
    machineZStartHeight: '',
    machineZToolOffset: 0,
    macros: {
        ['*GotoXY0']: {label: 'Goto XY zero', gcode: 'G0 X0Y0', keybinding: 'ctrl+f1', _locked: false},
        ['*LaserOff']: {label: 'LASER OFF', gcode: 'M5', keybinding: 'ctrl+f2', _locked: false},
    },
    pxPerInch: 96,
    showMachine: false,
    toolCncMode: false,
    toolCreateEmptyOps: false,
    toolDisplayCache: false,
    toolFeedUnits: 'mm/min',
    toolGridHeight: 500,
    toolGridMajorSpacing: 50,
    toolGridMinorSpacing: 10,
    toolGridWidth: 500,
    toolImagePosition: 'BL',
    toolSafetyLockDisabled: true,
    toolTestDuration: 0,
    toolTestSValue: 1,
    toolUseGamepad: false,
    toolUseNumpad: false,
    toolVideoDevice: null,
    toolVideoFov: {
        x: 1,
        y: 1,
    },
    toolVideoLens: {
        F: 1,
        a: 1,
        b: 1,
        scale: 1,
    },
    toolVideoOMR: false,
    toolVideoOMRMarkerSize: 20,
    toolVideoOMROffsetX: 0,
    toolVideoOMROffsetY: 0,
    toolVideoPerspective: {
        enabled: false,
    },
    toolVideoResolution: '720p(HD)',
    toolWebcamUrl: '',
    uiFcDrag: null,
    __latestRelease: '2019-01-15T15:42:23Z',
    __selectedProfile: null,
    __version: '4.0.997',
}

export const defaultOperation: Operation = {
    aAxisDiameter: 0,
    brightness: 0,
    burnWhite: true,
    contrast: 0,
    cutRate: 0,
    cutWidth: 0,
    diagonal: false,
    direction: 'Conventional',
    dithering: false,
    documents: [],
    enabled: true,
    expanded: true,
    filterFillColor: null,
    filterStrokeColor: null,
    gamma: 0,
    grayscale: 'none',
    hookOperationEnd: '',
    hookOperationStart: '',
    hookPassEnd: '',
    hookPassStart: '',
    id: '',
    invertColor: false,
    joinPixel: true,
    laserDiameter: 0.2,
    laserPower: 100,
    laserPowerRange: {min: 0, max: 100},
    latheFace: true,
    latheFaceEndDiameter: 0,
    latheFinishDepth: 0,
    latheFinishExtraPasses: 0,
    latheFinishFeed: 0,
    latheRapidToDiameter: 0,
    latheRapidToZ: 0,
    latheRoughingDepth: 0,
    latheRoughingFeed: 0,
    latheStartZ: 0,
    latheToolBackSide: false,
    latheTurns: [],
    lineAngle: 0,
    lineDistance: 0,
    margin: 0,
    millEndZ: 0,
    millRapidZ: 0,
    millStartZ: 0,
    name: 'Main',
    overScan: 0,
    passDepth: 0,
    passes: 1,
    plungeRate: 0,
    ramp: false,
    segmentLength: 0,
    shadesOfGray: 256,
    smoothing: false,
    startHeight: '',
    stepOver: 40,
    tabDepth: 0,
    tabDocuments: [],
    toolAngle: 0,
    toolDiameter: 0,
    toolSpeed: 0,
    trimLine: true,
    type: 'Laser Cut',
    useA: false,
    useBlower: false,
    verboseGcode: false,
    _docs_visible: true,
}